apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: togethergo-gateway
  namespace: consul
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  gatewayClassName: consul
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      # Add hostname: togethergo.example.com after DNS is ready.
      allowedRoutes:
        namespaces:
          from: All

