"""Dump the OpenAPI document to contracts/openapi/identity.yaml.

    python -m app.openapi ../../contracts/openapi/identity.yaml

Generated rather than hand-written, so the published contract cannot drift
away from the routes and Pydantic models that actually serve it. Building the
document needs a settings object but never opens a connection, so the values
below are placeholders — the lifespan does not run.
"""

from __future__ import annotations

import json
import sys
import tempfile
from pathlib import Path

import yaml
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

from app.config import Settings
from app.main import create_app


def _throwaway_key() -> Path:
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    path = Path(tempfile.mkdtemp()) / "openapi.pem"
    path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.PKCS8,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )
    return path


def main(destination: str) -> None:
    settings = Settings(
        IDENTITY_DATABASE_URL="postgresql+asyncpg://identity_user@postgres:5432/identity_db",
        REDIS_URL="redis://redis:6379/0",
        RABBITMQ_URL="amqp://togethergo@rabbitmq:5672/",
        JWT_PRIVATE_KEY_PATH=_throwaway_key(),
        JWT_KEY_ID="dev-key-1",
        INTERNAL_API_TOKEN="openapi-placeholder-token",
        LOG_LEVEL="warning",
    )
    document = create_app(settings).openapi()
    document["servers"] = [
        {"url": "http://localhost:8080", "description": "gateway"},
        {"url": "http://identity:8001", "description": "direct, internal network only"},
    ]

    out = Path(destination)
    out.parent.mkdir(parents=True, exist_ok=True)
    # round_trip through JSON so anything Pydantic emitted as a custom type
    # becomes plain YAML scalars.
    out.write_text(
        "# Generated by `make openapi-identity`. Do not edit by hand.\n"
        + yaml.safe_dump(json.loads(json.dumps(document)), sort_keys=False, width=100)
    )
    print(f"wrote {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "identity.yaml")
