{{- range $name, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "togethergo.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
{{- end }}
{{- end }}
