from __future__ import annotations

import datetime as dt
import uuid
from typing import Any

from sqlalchemy import Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class Outbox(Base):
    """Transactional outbox — identical contract to the Go services.

    `id` is generated by the writer, not the database, because it becomes the
    envelope's `event_id`: a row republished after a relay crash carries the
    same id and consumers deduplicate on it.
    """

    __tablename__ = "outbox"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)
    aggregate_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), nullable=False)
    event_type: Mapped[str] = mapped_column(Text, nullable=False)
    # The envelope's `payload` object only. The relay builds the envelope.
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[dt.datetime] = mapped_column(server_default=func.now(), nullable=False)
    published_at: Mapped[dt.datetime | None] = mapped_column()
